name: ThinkBayes2
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - jupyter
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - statsmodels
  - scipy
  - "pymc>=6.0"
  - "arviz>=1.0"
  - python-graphviz
  - lxml
  - xlrd
  - html5lib
  - pytables
  - nbconvert
  - pip
  - empiricaldist>=0.6.7
