name: ThinkBayes
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - jupyter
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - statsmodels
  - scipy
  - "pymc>=5.16,<6"
  - "arviz>=0.17,<1"
  - pip
  - pip:
    - empiricaldist
